//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Agenda.ClassActivityDataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassActivityData", Namespace="http://schemas.datacontract.org/2004/07/TellMe.Web.Wcf")]
    [System.SerializableAttribute()]
    public partial class ClassActivityData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] BooksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClassIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomeWorkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeacherIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] Books {
            get {
                return this.BooksField;
            }
            set {
                if ((object.ReferenceEquals(this.BooksField, value) != true)) {
                    this.BooksField = value;
                    this.RaisePropertyChanged("Books");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClassId {
            get {
                return this.ClassIdField;
            }
            set {
                if ((this.ClassIdField.Equals(value) != true)) {
                    this.ClassIdField = value;
                    this.RaisePropertyChanged("ClassId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomeWork {
            get {
                return this.HomeWorkField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeWorkField, value) != true)) {
                    this.HomeWorkField = value;
                    this.RaisePropertyChanged("HomeWork");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeacherId {
            get {
                return this.TeacherIdField;
            }
            set {
                if ((this.TeacherIdField.Equals(value) != true)) {
                    this.TeacherIdField = value;
                    this.RaisePropertyChanged("TeacherId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassActivityDescriptiveData", Namespace="http://schemas.datacontract.org/2004/07/TellMe.Web.Wcf")]
    [System.SerializableAttribute()]
    public partial class ClassActivityDescriptiveData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] BooksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomeWorkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Books {
            get {
                return this.BooksField;
            }
            set {
                if ((object.ReferenceEquals(this.BooksField, value) != true)) {
                    this.BooksField = value;
                    this.RaisePropertyChanged("Books");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClassName {
            get {
                return this.ClassNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassNameField, value) != true)) {
                    this.ClassNameField = value;
                    this.RaisePropertyChanged("ClassName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomeWork {
            get {
                return this.HomeWorkField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeWorkField, value) != true)) {
                    this.HomeWorkField = value;
                    this.RaisePropertyChanged("HomeWork");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeacherName {
            get {
                return this.TeacherNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherNameField, value) != true)) {
                    this.TeacherNameField = value;
                    this.RaisePropertyChanged("TeacherName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClassActivityDataService.IClassActivityDataService")]
    public interface IClassActivityDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassActivityDataService/Save", ReplyAction="http://tempuri.org/IClassActivityDataService/SaveResponse")]
        void Save(Common.Agenda.ClassActivityDataService.ClassActivityData classData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassActivityDataService/Save", ReplyAction="http://tempuri.org/IClassActivityDataService/SaveResponse")]
        System.Threading.Tasks.Task SaveAsync(Common.Agenda.ClassActivityDataService.ClassActivityData classData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassActivityDataService/GetByClassIds", ReplyAction="http://tempuri.org/IClassActivityDataService/GetByClassIdsResponse")]
        Common.Agenda.ClassActivityDataService.ClassActivityDescriptiveData[] GetByClassIds(System.DateTime date, int[] classIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassActivityDataService/GetByClassIds", ReplyAction="http://tempuri.org/IClassActivityDataService/GetByClassIdsResponse")]
        System.Threading.Tasks.Task<Common.Agenda.ClassActivityDataService.ClassActivityDescriptiveData[]> GetByClassIdsAsync(System.DateTime date, int[] classIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassActivityDataService/GetByClassNames", ReplyAction="http://tempuri.org/IClassActivityDataService/GetByClassNamesResponse")]
        Common.Agenda.ClassActivityDataService.ClassActivityDescriptiveData[] GetByClassNames(System.DateTime date, string[] classNames);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassActivityDataService/GetByClassNames", ReplyAction="http://tempuri.org/IClassActivityDataService/GetByClassNamesResponse")]
        System.Threading.Tasks.Task<Common.Agenda.ClassActivityDataService.ClassActivityDescriptiveData[]> GetByClassNamesAsync(System.DateTime date, string[] classNames);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClassActivityDataServiceChannel : Common.Agenda.ClassActivityDataService.IClassActivityDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClassActivityDataServiceClient : System.ServiceModel.ClientBase<Common.Agenda.ClassActivityDataService.IClassActivityDataService>, Common.Agenda.ClassActivityDataService.IClassActivityDataService {
        
        public ClassActivityDataServiceClient() {
        }
        
        public ClassActivityDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClassActivityDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClassActivityDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClassActivityDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Save(Common.Agenda.ClassActivityDataService.ClassActivityData classData) {
            base.Channel.Save(classData);
        }
        
        public System.Threading.Tasks.Task SaveAsync(Common.Agenda.ClassActivityDataService.ClassActivityData classData) {
            return base.Channel.SaveAsync(classData);
        }
        
        public Common.Agenda.ClassActivityDataService.ClassActivityDescriptiveData[] GetByClassIds(System.DateTime date, int[] classIds) {
            return base.Channel.GetByClassIds(date, classIds);
        }
        
        public System.Threading.Tasks.Task<Common.Agenda.ClassActivityDataService.ClassActivityDescriptiveData[]> GetByClassIdsAsync(System.DateTime date, int[] classIds) {
            return base.Channel.GetByClassIdsAsync(date, classIds);
        }
        
        public Common.Agenda.ClassActivityDataService.ClassActivityDescriptiveData[] GetByClassNames(System.DateTime date, string[] classNames) {
            return base.Channel.GetByClassNames(date, classNames);
        }
        
        public System.Threading.Tasks.Task<Common.Agenda.ClassActivityDataService.ClassActivityDescriptiveData[]> GetByClassNamesAsync(System.DateTime date, string[] classNames) {
            return base.Channel.GetByClassNamesAsync(date, classNames);
        }
    }
}
