//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Agenda.ClassDataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassData", Namespace="http://schemas.datacontract.org/2004/07/TellMe.Web.Wcf")]
    [System.SerializableAttribute()]
    public partial class ClassData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClassDataService.IClassDataService")]
    public interface IClassDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassDataService/Insert", ReplyAction="http://tempuri.org/IClassDataService/InsertResponse")]
        Common.Agenda.ClassDataService.ClassData Insert(Common.Agenda.ClassDataService.ClassData classData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassDataService/Insert", ReplyAction="http://tempuri.org/IClassDataService/InsertResponse")]
        System.Threading.Tasks.Task<Common.Agenda.ClassDataService.ClassData> InsertAsync(Common.Agenda.ClassDataService.ClassData classData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassDataService/Update", ReplyAction="http://tempuri.org/IClassDataService/UpdateResponse")]
        void Update(Common.Agenda.ClassDataService.ClassData classData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassDataService/Update", ReplyAction="http://tempuri.org/IClassDataService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(Common.Agenda.ClassDataService.ClassData classData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassDataService/Delete", ReplyAction="http://tempuri.org/IClassDataService/DeleteResponse")]
        void Delete(Common.Agenda.ClassDataService.ClassData classData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassDataService/Delete", ReplyAction="http://tempuri.org/IClassDataService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(Common.Agenda.ClassDataService.ClassData classData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClassDataServiceChannel : Common.Agenda.ClassDataService.IClassDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClassDataServiceClient : System.ServiceModel.ClientBase<Common.Agenda.ClassDataService.IClassDataService>, Common.Agenda.ClassDataService.IClassDataService {
        
        public ClassDataServiceClient() {
        }
        
        public ClassDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClassDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClassDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClassDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Common.Agenda.ClassDataService.ClassData Insert(Common.Agenda.ClassDataService.ClassData classData) {
            return base.Channel.Insert(classData);
        }
        
        public System.Threading.Tasks.Task<Common.Agenda.ClassDataService.ClassData> InsertAsync(Common.Agenda.ClassDataService.ClassData classData) {
            return base.Channel.InsertAsync(classData);
        }
        
        public void Update(Common.Agenda.ClassDataService.ClassData classData) {
            base.Channel.Update(classData);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(Common.Agenda.ClassDataService.ClassData classData) {
            return base.Channel.UpdateAsync(classData);
        }
        
        public void Delete(Common.Agenda.ClassDataService.ClassData classData) {
            base.Channel.Delete(classData);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(Common.Agenda.ClassDataService.ClassData classData) {
            return base.Channel.DeleteAsync(classData);
        }
    }
}
